### ISSUE TITLE
Coco Rominger

### ISSUE THREAD

**Issue by cocorominger** [umiami-web-design/project-html#22]

**Comment by cocorominger** [comment]
file:///Users/cocorominger/Documents/GitHub/cocorominger.github.io/resume.html#education

**Comment by cocorominger** [comment]
file:///Users/cocorominger/Documents/GitHub/cocorominger.github.io/resume.html#education

**Comment by erinbrown** [comment]
Coco, I can’t read files on your computer. You need to resubmit.

**Comment by ebrown15** [comment]
Coco, I can’t read files on your computer. You need to resubmit.

**Comment by cocorominger** [comment]
Hi Professor Brown,

I apologize for the delay in response. I was at work and just got your email. 

I realized that my first upload was incorrect and I just want to explain what happened. It’s a little confusing but, something went wrong when I was saving my first resume.html file and it wouldn’t link in github desktop.

I re-coded on a new file in atom and then tried to change the name and override my first resume.html file.

For some reason my new files wouldn’t connect to github desktop it showed an orange circle next to it instead of green sign, even though the code was the same as before. So I googled what to do and it said to republish it to master. So that is why you may see duplicates of my code (I tried this multiple times in hopes that it would correct itself).

Unfortunately, my photo didn’t sync as well and I was unable to rename the file in the original code so that is why it was my image is not appearing, but I wrote in the correct code for image sourcing.

I am so sorry for this inconvenience, 

I am still confused as to how this got messed up. 

I uploaded the new link that does work.
Sorry for taking up more of your time,

Coco Rominger
