### ISSUE TITLE
Taylor de Tuya

### ISSUE THREAD

**Issue by TaylordeTuya** [umiami-web-design/project-html#38]
http://TaylordeTuya.github.io/resume.html

**Comment by thegeekprof** [comment]
Will email feedback soon.

**Comment by TaylordeTuya** [comment]
My grade is a 0?

**Comment by TaylordeTuya** [comment]
I don't understand... I did the assignment and turned it in. Please email me back as soon as possible. 

Thanks,
Taylor de Tuya
